# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 8030, host: 8030

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    # OPTIONS
    BUILD_SOURCE=
    HOST="https://chat.example.com"
    MONGO_URL="mongodb://localhost:27017/rocketchat"
    #MONGO_OPLOG_URL="mongodb://localhost:27017/local"
    ROOT_URL="${HOST}"
    PORT="8030"
    
    # SYSTEM CONFIGURATION
    curl -#L https://deb.nodesource.com/setup_0.10 -o setup_node.sh
    bash setup_node.sh

    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
    echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.0.list

    apt-get update
    apt-get install -y nodejs mongodb-org graphicsmagick build-essential libssl-dev unzip

    npm install n -g
    npm install pm2 -g
 
    NODEJS_VERSION=$(dpkg-query --showformat='${Version}' --show nodejs | cut -d- -f1)
    n "${NODEJS_VERSION}"

    if [ -n "${BUILD_SOURCE}" ]; then
        curl https://install.meteor.com/ | sh
    fi

    pm2 startup

    mkdir -p /var/www/rocket.chat
    mkdir -p /var/log/rocket.chat

    # DEPLOY
    cd /var/www/
    if [ -n "${BUILD_SOURCE}" ]; then
        # Install from source
        curl -#L -O https://github.com/RocketChat/Rocket.Chat/archive/master.zip
        unzip master.zip
        mv Rocket.Chat-master/* rocket.chat
    else
        # Install from release
        curl -#L https://rocket.chat/releases/latest/download -o rocket.chat.tgz
        tar zxf rocket.chat.tgz -C rocket.chat
    fi

    cd ./rocket.chat
    if [ -n "${BUILD_SOURCE}" ]; then
        # Install from source
        meteor build --server "$HOST" --directory .
    fi

    cd ./bundle/programs/server
    npm install

    cd ../..

    rm -f pm2-rocket-chat.json
    echo '{'                                                     > pm2-rocket-chat.json
    echo '  "apps": [{'                                         >> pm2-rocket-chat.json
    echo '    "name": "rocket.chat",'                           >> pm2-rocket-chat.json
    echo '    "script": "/var/www/rocket.chat/bundle/main.js",' >> pm2-rocket-chat.json
    echo '    "out_file": "/var/log/rocket.chat/app.log",'      >> pm2-rocket-chat.json
    echo '    "error_file": "/var/log/rocket.chat/err.log",'    >> pm2-rocket-chat.json
    echo "    \\"port\\": \\"$PORT\\","                         >> pm2-rocket-chat.json
    echo '    "env": {'                                         >> pm2-rocket-chat.json
    echo "      \\"MONGO_URL\\": \\"$MONGO_URL\\","             >> pm2-rocket-chat.json
    if [ -n "${MONGO_OPLOG_URL}" ]; then
    # Use Mongo ReplicaSet
    echo "      \\"MONGO_OPLOG_URL\\": \\"$MONGO_OPLOG_URL\\"," >> pm2-rocket-chat.json
    fi
    echo "      \\"ROOT_URL\\": \\"$ROOT_URL\\","               >> pm2-rocket-chat.json
    echo "      \\"PORT\\": \\"$PORT\\""                        >> pm2-rocket-chat.json
    echo '    }'                                                >> pm2-rocket-chat.json
    echo '  }]'                                                 >> pm2-rocket-chat.json
    echo '}'                                                    >> pm2-rocket-chat.json

    pm2 start pm2-rocket-chat.json
    pm2 save
  SHELL
end
